### ISSUE TITLE
Action Mailer error

### ISSUE THREAD

**Issue by silvercrow27** [awwa/sendgrid4r#14]
Hello, why am I getting this errors whenever I add sendgrid4r in my Gemfile?

```
/home/laziendo/.rvm/gems/ruby-2.2.2/gems/sendgrid4r-1.2.0/lib/client.rb:19: warning: circular argument reference - username
/home/laziendo/.rvm/gems/ruby-2.2.2/gems/sendgrid4r-1.2.0/lib/client.rb:19: warning: circular argument reference - password
/home/laziendo/.rvm/gems/ruby-2.2.2/gems/sendgrid4r-1.2.0/lib/auth.rb:12: warning: circular argument reference - username
/home/laziendo/.rvm/gems/ruby-2.2.2/gems/sendgrid4r-1.2.0/lib/auth.rb:12: warning: circular argument reference - password
/home/laziendo/.rvm/gems/ruby-2.2.2/gems/sendgrid4r-1.2.0/lib/sendgrid4r/rest/users/users.rb:45: warning: circular argument reference - params
=> Booting WEBrick
=> Rails 4.1.7 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Exiting
/home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/actionmailer-4.1.7/lib/action_mailer/delivery_methods.rb:44:in `<module:ClassMethods>': uninitialized constant ActionMailer::DeliveryMethods::ClassMethods::Mail (NameError)
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/actionmailer-4.1.7/lib/action_mailer/delivery_methods.rb:42:in `<module:DeliveryMethods>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/actionmailer-4.1.7/lib/action_mailer/delivery_methods.rb:6:in `<module:ActionMailer>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/actionmailer-4.1.7/lib/action_mailer/delivery_methods.rb:3:in `<top (required)>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:402:in `<class:Base>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:401:in `<module:ActionMailer>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/actionmailer-4.1.7/lib/action_mailer/base.rb:9:in `<top (required)>'
	from /home/laziendo/Desktop/stuffs/project103/config/initializers/mail.rb:3:in `<top (required)>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/activesupport-4.1.7/lib/active_support/notifications.rb:161:in `instrument'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/engine.rb:647:in `load_config_initializer'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/engine.rb:611:in `each'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/initializable.rb:30:in `run'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/initializable.rb:44:in `each'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/laziendo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/application.rb:300:in `initialize!'
	from /home/laziendo/Desktop/stuffs/project103/config/environment.rb:5:in `<top (required)>'
	from /home/laziendo/Desktop/stuffs/project103/config.ru:3:in `require'
	from /home/laziendo/Desktop/stuffs/project103/config.ru:3:in `block in <main>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/builder.rb:55:in `instance_eval'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/builder.rb:55:in `initialize'
	from /home/laziendo/Desktop/stuffs/project103/config.ru:in `new'
	from /home/laziendo/Desktop/stuffs/project103/config.ru:in `<main>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/builder.rb:49:in `eval'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/builder.rb:49:in `new_from_string'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/builder.rb:40:in `parse_file'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/server.rb:277:in `build_app_and_options_from_config'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/server.rb:199:in `app'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands/server.rb:50:in `app'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/rack-1.5.3/lib/rack/server.rb:314:in `wrapped_app'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands/server.rb:130:in `log_to_stdout'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands/server.rb:67:in `start'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/laziendo/Desktop/stuffs/project103/bin/rails:8:in `require'
	from /home/laziendo/Desktop/stuffs/project103/bin/rails:8:in `<top (required)>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `load'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/spring-1.3.6/lib/spring/client/rails.rb:28:in `call'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/spring-1.3.6/lib/spring/client/command.rb:7:in `call'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/spring-1.3.6/lib/spring/client.rb:26:in `run'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/gems/spring-1.3.6/bin/spring:48:in `<top (required)>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/bin/spring:23:in `load'
	from /home/laziendo/.rvm/gems/ruby-2.2.2@global/bin/spring:23:in `<main>'
	from /home/laziendo/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/laziendo/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by awwa** [comment]
It seems ruby 2.2.x treats as warn circular argument reference.
https://bugs.ruby-lang.org/issues/10314
You can ignore this warnings.

I have created a PR for this problem.
https://github.com/awwa/sendgrid4r/pull/15
This will be fix in next version.

**Comment by silvercrow27** [comment]
Ok thanks the circular argument reference is gone now. But I still getting action mailer error.

**Comment by silvercrow27** [comment]
Problem Solved I just add mail gem in my gemfile.

**Comment by davesherratt** [comment]
@silvercrow27 which gem did you add, having the same issue and it won't start the application.

**Comment by silvercrow27** [comment]
I added 
```
gem 'mail'
```

**Comment by gmhawash** [comment]
I put `require: false` in the Gemfile and just require it in the file I am using it and that works for me.

**Comment by awwa** [comment]
@nsantiago2719 
This problem might be resolved from ver.1.5.1.
Could you try this?
https://rubygems.org/gems/sendgrid4r/versions/1.5.1
